FROM python:3.11.5
COPY app_requirements.txt app/app_requirements.txt
WORKDIR /app
RUN pip install -r app_requirements.txt
COPY . /app
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000" ,"--reload"]